swagger: "2.0"
info:
  description: "File Server"
  version: "1.0.0"
  title:  "File Server"
basePath: /
tags:
- name: "files"
  description: "All functionalities about file storage"
schemes:
- "https"
- "http"
consumes:
  - application/json
produces:
  - application/json


securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
# Paths supported by the server application
paths:
  /files:
    get:
      summary: Reads the entire list of files.
      description: Access to all files
      security:
        - Bearer: []
      operationId: get_files
      tags:
        - files
      parameters:
        - name: include
          in: query
          description: "'all' for own and shared files, 'own' for only files ubloaded by authorized user, 'shared' for only files from other users the autorized user has access to."
          required: false
          type: string
      responses:
        200:
          description: dictionary with to lists of fileobject-descriptions
          schema:
            type: object
            properties:
              own_files:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    size:
                      type: integer
                    upload_date:
                      type: string
                    id:
                      type: integer
                    user:
                      type: string
                    shared_with:
                      type: array
                      items:
                        type: integer

              shared_files:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    size:
                      type: integer
                    upload_date:
                      type: string
                    id:
                      type: integer
                    user:
                      type: string
                    shared_with:
                      type: array
                      items:
                        type: integer
        401:
          description: Unauthorized
        403:
          description: Forbidden- insufficient access rights

    post:
      summary: Uploads a new file and adds information about which users have the right to download it.
      description: Add a new file
      security:
        - Bearer: []
      operationId: add_file
      tags:
        - files
      consumes:
        - multipart/form-data
      parameters:
        - name: shared_with
          in: formData
          description: array of users that can access this file
          required: false
          type: array
          items:
            type: integer
          uniqueItems: true
        - name: file_content
          in: formData
          type: file
          description: the file to upload
          required: true
      responses:
        201:
          description: Successfully created file
          schema:
            properties:
              name:
                type: string
              size:
                type: integer
              upload_date:
                type: string
              id:
                type: integer
              user:
                type: string
              shared_with:
                type: array
                items:
                  type: integer
        400:
          description: Missing/empty file object
        401:
          description: Unauthorized- not logged in
        403:
          description: Forbidden- insufficient access rights
  /files/{file_id}:
    get:
      summary: Get all informations about a uploaded file from the database.
      description: Get one specific file by its id
      security:
        - Bearer: []
      operationId: get_single_file
      tags:
        - files
      parameters:
        - name: file_id
          in: path
          description: Id of the file
          type: integer
          required: True
      responses:
        200:
          description: Successfully found and delivered file information
          schema:
            properties:
              name:
                type: string
              size:
                type: integer
              upload_date:
                type: string
                format: date-time
              id:
                type: integer
              user:
                type: string
              shared_with:
                type: array
                items:
                  type: integer
        401:
          description: Unauthorized
        403:
          description: Forbidden- insufficient access rights
        404:
          description: Not found


    delete:
      summary: Deletes a file specified by its file_id. Can only be done by the owner.
      description: Delete a file
      security:
        - Bearer: []
      operationId: delete_file
      tags:
        - files
      parameters:
        - name: file_id
          in: path
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted a file from db
        401:
          description: Unauthorized
        403:
          description: Forbidden- insufficient access rights
        404:
          description: Not found- no file with this id in the database

    patch:
      summary: Change a files content and/or the users it is shared with.
      description: Update a file.
      security:
        - Bearer: []
      operationId: change_filename_and_shared
      tags:
        - files
      consumes:
        - application/json
      parameters:
        - name: file_id
          in: path
          type: integer
          required: True
        - name: file_info
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              shared_with:
                type: array
                items:
                  type: integer
          required: True
      responses:
        200:
          description: Successfully changed file
          schema:
            properties:
              name:
                type: string
              size:
                type: integer
              upload_date:
                type: string
              id:
                type: integer
              user:
                type: string
              shared_with:
                type: array
                items:
                  type: integer
        400:
          description: Missing/empty file object
        401:
          description: Unauthorized
        403:
          description: Forbidden- insufficient access rights
        404:
          description: Not found

  /files/{id}/download:
    get:
      summary: Downloads the file
      description: Get the content of the file as provided by flask.send_file.
      security:
        - Bearer: []
      operationId: get_download
      tags:
        - files
      parameters:
        - name: id
          in: path
          description: Id of the file
          type: integer
          required: True
      responses:
        401:
          description: Unauthorized
        403:
          description: Forbidden- insufficient access rights
        404:
          description: Not found